name: Automacao Inadimplentes
on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Atualizado para 3.11

      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Run Automation
        env:
          EVO_LOGIN: ${{ secrets.EVO_LOGIN }}
          EVO_SENHA: ${{ secrets.EVO_SENHA }}
          GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        run: python main.py

      # ISSO AQUI SALVA A FOTO SE DER ERRO
      - name: Salvar Print do Erro
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Print-do-Erro
          path: debug_error.png
