name: Automacao Inadimplentes
on:
  schedule:
    # Agendado para as 08:00 AM do Brasil (11:00 UTC)
    - cron: '0 11 * * *'
  # Permite que você rode manualmente clicando em um botão
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Run Automation
        env:
          EVO_LOGIN: ${{ secrets.EVO_LOGIN }}
          EVO_SENHA: ${{ secrets.EVO_SENHA }}
          GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        run: python main.py
